# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-10-07 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20181007_0216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HasaTag',
            new_name='HashTag',
        ),
    ]
